[context.staging]
  [context.staging.environment]
    REACT_APP_BACKEND_API='https://staging.api.acquity.io/v1/'

[context.production]
  [context.production.environment]
    REACT_APP_BACKEND_API='https://api.acquity.io/v1/'

[context.deploy-preview.environment]
  REACT_APP_BACKEND_API='https://staging.api.acquity.io/v1/'
